"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob

from setuptools import setup

APP = ['main.py']
DATA_FILES = [('images', glob.glob('images/*.*')), ('Applescripts', glob.glob('Applescripts/*.*'))]
OPTIONS = {'packages': ['rumps'], 'plist': {'LSUIElement': True}, 'iconfile':'icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
